//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPTS
    {
        public int MAPTS { get; set; }
        public int MACTS { get; set; }
        public int MAPMS { get; set; }
        public Nullable<decimal> TIENPHAT { get; set; }
        public int MASACH { get; set; }
        public string TENSACH { get; set; }
        public DateTime NGMUON { get; set; }

        public virtual CTSACH CTSACH { get; set; }
        public virtual PHIEUMUONSACH PHIEUMUONSACH { get; set; }
        public virtual PHIEUTRASACH PHIEUTRASACH { get; set; }
    }
}
