//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTSACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTSACH()
        {
            this.PHIEUMUONSACH = new HashSet<PHIEUMUONSACH>();
            this.PHIEUTRASACH = new HashSet<PHIEUTRASACH>();
        }
    
        public int MACTS { get; set; }
        public Nullable<int> MASACH { get; set; }
        public Nullable<int> MATT { get; set; }
        public string VITRI { get; set; }
        public Nullable<decimal> GIABIA { get; set; }
        public Nullable<decimal> GIANHAP { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public Nullable<int> NGUOINHAP { get; set; }
        public string QRCODE { get; set; }
    
        public virtual SACH SACH { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        public virtual TINHTRANG TINHTRANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUMUONSACH> PHIEUMUONSACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTRASACH> PHIEUTRASACH { get; set; }
    }
}
