//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    using Caliburn.Micro;
    public partial class LOAIDOCGIA:PropertyChangedBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAIDOCGIA()
        {
            this.DOCGIA = new HashSet<DOCGIA>();
        }
    
        public int MALDG { get; set; }
        private string _LOAIDOCGIA1;
        public string LOAIDOCGIA1
        {
            get { return _LOAIDOCGIA1; }
            set { _LOAIDOCGIA1 = value; NotifyOfPropertyChange("LOAIDOCGIA1"); }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCGIA> DOCGIA { get; set; }
    }
}
