//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTRASACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUTRASACH()
        {
            this.CTPTS = new HashSet<CTPTS>();
        }
    
        public int MAPTS { get; set; }
        public Nullable<int> MADG { get; set; }
        public Nullable<System.DateTime> NGTRASACH { get; set; }
        public Nullable<int> NGUOILAP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPTS> CTPTS { get; set; }
        public virtual DOCGIA DOCGIA { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
