//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHUTIENPHAT
    {
        public int MAPTTP { get; set; }
        public Nullable<int> MADG { get; set; }
        public Nullable<decimal> SOTIENTHU { get; set; }
        public Nullable<System.DateTime> NGTHU { get; set; }
        public Nullable<int> NGUOILAP { get; set; }
    
        public virtual DOCGIA DOCGIA { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
