//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLTVEntities : DbContext
    {
        public QLTVEntities()
            : base("name=QLTVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTSACH> CTSACH { get; set; }
        public virtual DbSet<DOCGIA> DOCGIA { get; set; }
        public virtual DbSet<LOAIDOCGIA> LOAIDOCGIA { get; set; }
        public virtual DbSet<NHAXUATBAN> NHAXUATBAN { get; set; }
        public virtual DbSet<PHIEUMUONSACH> PHIEUMUONSACH { get; set; }
        public virtual DbSet<PHIEUNHAPSACH> PHIEUNHAPSACH { get; set; }
        public virtual DbSet<PHIEUTHUTIENPHAT> PHIEUTHUTIENPHAT { get; set; }
        public virtual DbSet<PHIEUTRASACH> PHIEUTRASACH { get; set; }
        public virtual DbSet<SACH> SACH { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TACGIA> TACGIA { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOAN { get; set; }
        public virtual DbSet<TINHTRANG> TINHTRANG { get; set; }
        public virtual DbSet<THELOAI> THELOAI { get; set; }
    }
}
