//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYDINH
    {
        public Nullable<int> SACHMUONTOIDA { get; set; }
        public Nullable<int> NGAYMUON { get; set; }
        public Nullable<decimal> TIENPHAT { get; set; }
        public Nullable<int> KHOANGCACHXB { get; set; }
        public Nullable<int> TUOITOIDA { get; set; }
        public Nullable<int> TUOITOITHIEU { get; set; }
        public Nullable<decimal> TIENPHATTOIDA { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> NGAYSUA { get; set; }
        public Nullable<int> NGUOISUA { get; set; }
        public Nullable<int> THOIHANTHE { get; set; }
    }
}
