//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    using Caliburn.Micro;
    public partial class TAIKHOAN: PropertyChangedBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAIKHOAN()
        {
            this.PHIEUMUONSACH = new HashSet<PHIEUMUONSACH>();
            this.PHIEUNHAPSACH = new HashSet<PHIEUNHAPSACH>();
            this.PHIEUTHUTIENPHAT = new HashSet<PHIEUTHUTIENPHAT>();
            this.PHIEUTRASACH = new HashSet<PHIEUTRASACH>();
        }
        public TAIKHOAN(TAIKHOAN tk)
        {
            this.MATK = tk.MATK;
            this.TAIKHOAN1 = tk.TAIKHOAN1;
            this.MATKHAU = tk.MATKHAU;
            this.NGDK = tk.NGDK;
            this.HOTEN = tk.HOTEN;
            this.DCHI = tk.DCHI;
            this.EMAIL = tk.EMAIL;
            this.HINHANH = tk.HINHANH;          
        }
        public int MATK { get; set; }
        private string _TAIKHOAN1;
        public string TAIKHOAN1
        {
            get
            {
                return _TAIKHOAN1;
            }
            set
            {
                _TAIKHOAN1 = value;
                NotifyOfPropertyChange("TAIKHOAN1");
            }
        }
        private string _MATKHAU;
        public string MATKHAU
        {
            get
            {
                return _MATKHAU;
            }
            set
            {
                _MATKHAU = value;
                NotifyOfPropertyChange("MATKHAU");
            }
        }
        private Nullable<System.DateTime> _NGDK;
        public Nullable<System.DateTime> NGDK
        {
            get
            {
                return _NGDK;
            }
            set
            {
                _NGDK = value;
                NotifyOfPropertyChange("NGDK");
            }
        }
        private string _HOTEN;
        public string HOTEN
        {
            get
            {
                return _HOTEN;
            }
            set
            {
                _HOTEN = value;
                NotifyOfPropertyChange("HOTEN");
            }
        }
        private string _DCHI;
        public string DCHI
        {
            get
            {
                return _DCHI;
            }
            set
            {
                _DCHI = value;
                NotifyOfPropertyChange("DCHI");
            }
        }
        private string _EMAIL;
        public string EMAIL
        {
            get
            {
                return _EMAIL;
            }
            set
            {
                _EMAIL = value;
                NotifyOfPropertyChange("EMAIL");
            }
        }
        private string _HINHANH;
        public string HINHANH
        {
            get
            {
                return _HINHANH;
            }
            set
            {
                _HINHANH = value;
                NotifyOfPropertyChange("_HINHANH");
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUMUONSACH> PHIEUMUONSACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUNHAPSACH> PHIEUNHAPSACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTHUTIENPHAT> PHIEUTHUTIENPHAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTRASACH> PHIEUTRASACH { get; set; }
    }
}
