//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    using Caliburn.Micro;
    public partial class TINHTRANG:PropertyChangedBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TINHTRANG()
        {
            this.CTSACH = new HashSet<CTSACH>();
        }
    
        public int MATT { get; set; }

        private string _TINHTRANG1;
        public string TINHTRANG1
        {
            get { return _TINHTRANG1; }
            set { _TINHTRANG1 = value; NotifyOfPropertyChange("TINHTRANG1"); }
        }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTSACH> CTSACH { get; set; }
    }
}
